import "./globals.css";

export const metadata = {
  title: "Live Code Editor",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="font-default" cz-shortcut-listen="true">
        {children}
      </body>
    </html>
  );
}
