import "./globals.css";
import { ToastContainer } from "react-toastify";

export const metadata = {
  title: "Live Code Editor",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* <head /> */}
      <body className="font-default" cz-shortcut-listen="true">
        {children}
        <ToastContainer position="top-right" autoClose={3000} />
      </body>
    </html>
  );
}
